### ISSUE TITLE
Get Total Bytes Sent/Received

### ISSUE THREAD

**Issue by Pheric** [m-lab/ndt5-client-go#11]
I am using the NDTv5 client on Alpine Linux. My goal is to find the total number of bytes sent and received by a test. In the program output, I see a number of interesting fields, including:

```
web100: DataBytesOut: 0
web100: PktsOut: 99773
web100: AckPktsIn: 0
web100: TCPInfo.BytesAcked: 142008256
web100: TCPInfo.BytesReceived: 0
web100: TCPInfo.SegsOut: 99773
web100: TCPInfo.SegsIn: 34542
web100: TCPInfo.DataSegsIn: 0
web100: TCPInfo.DataSegsOut: 99773
web100: TCPInfo.BytesSent: 144471304
```

I would expect TCPInfo.BytesSent and TCPInfo.BytesReceived to be what I need, but BytesReceived is zero. Where can I get the total bytes transmitted / received by the test?

**Comment by critzo** [comment]
I have replied to the message your team sent to support@measurementlab.net with more information, but in general we would recommend that you look at `ndt7-client-go` instead of using this repository for a new custom client.

As written in the [`ndt-server` repository's Readme on NDT5](https://github.com/m-lab/ndt-server/tree/master/ndt5):

> we support existing clients, but we will be adding no new functionality. If you are reading this and trying to decide how to implement a speed test, use ndt7 and not the legacy, ndt5 protocol. The legacy protocol is deprecated. It will be supported until usage drops to very low levels, but it is also not recommended for new integrations or code.

You also may wish to consider following our work on the NDT7 JavaScript/NodeJS reference client:
https://github.com/m-lab/ndt7-js/pull/2

In both the Go and JS clients for NDT7, much richer JSON output is provided with values like BytesAcked and BytesReceived. The JS client will also support callback functions for further customizations.

**Comment by robertodauria** [comment]
This seems to happen on quite old kernels (e.g. 3.x) that do not provide all the TCPInfo fields correctly. A recent fix to ndt5-client makes sure it does not crash while writing the summary in such cases.

In general, the authority on how much data was transferred is always the received. For download tests, you can find the number of bytes received it in the TestResult struct: https://github.com/m-lab/ndt5-client-go/blob/2339aa62fcf183fbc0da9d674d66b8b0de5ae113/client.go#L194 which is available after the measurement as `client.Result` -- see: https://github.com/m-lab/ndt5-client-go/blob/2339aa62fcf183fbc0da9d674d66b8b0de5ae113/cmd/ndt5-client/main.go#L130 which uses it to create the summary at the end of the measurement. Please note that this is how much data was received at the application level, so excluding the TCP/TLS/WS overhead.

For upload measurements, the authority would be the server. If the server's kernel doesn't provide the TCPInfo metrics for a connection, there isn't much the client can do. One could modify it to save the amount of bytes "sent", but there is no guarantee that the server received all the bytes sent within the 10 seconds the measurement lasts for, thus it would always be inaccurate.

However, as Chris explained, the NDT5 protocol is deprecated at this point and we recommend moving to ndt7 wherever possible.
